import 'package:flutter/material.dart';

import '../../live_room_models.dart';

class GiftMockExtras {
  const GiftMockExtras._();

  static List<GiftItem> mergeWith(List<GiftItem> gifts) {
    const extras = <GiftItem>[
      GiftItem(
        id: 'rose_rain',
        name: 'Rose Rain',
        category: GiftCategory.classic,
        coins: 5,
        icon: Icons.local_florist_rounded,
        chatSymbol: '🌹',
        assetPath: 'assets/images/gifts/rose_rain.png',
        colors: [Color(0xFFFF6B9A), Color(0xFFFFC2D8)],
      ),
      GiftItem(
        id: 'star_kiss',
        name: 'Star Kiss',
        category: GiftCategory.classic,
        coins: 15,
        icon: Icons.star_rounded,
        chatSymbol: '⭐',
        assetPath: 'assets/images/gifts/star_kiss.png',
        colors: [Color(0xFFFFD166), Color(0xFFFF8A3D)],
      ),
      GiftItem(
        id: 'music_wave',
        name: 'Music Wave',
        category: GiftCategory.classic,
        coins: 29,
        icon: Icons.music_note_rounded,
        chatSymbol: '🎵',
        assetPath: 'assets/images/gifts/music_wave.png',
        colors: [Color(0xFF12C7B7), Color(0xFF6D5DF6)],
      ),
      GiftItem(
        id: 'lucky_packet',
        name: 'Lucky Packet',
        category: GiftCategory.lucky,
        coins: 39,
        icon: Icons.redeem_rounded,
        chatSymbol: '🧧',
        assetPath: 'assets/images/gifts/lucky_packet.png',
        colors: [Color(0xFFE84C72), Color(0xFFFFB545)],
      ),
      GiftItem(
        id: 'gold_spinner',
        name: 'Gold Spin',
        category: GiftCategory.lucky,
        coins: 59,
        icon: Icons.casino_rounded,
        chatSymbol: '🎰',
        assetPath: 'assets/images/gifts/gold_spinner.png',
        colors: [Color(0xFFFFD166), Color(0xFFC99A3B)],
      ),
      GiftItem(
        id: 'crystal_hunt',
        name: 'Crystal Hunt',
        category: GiftCategory.lucky,
        coins: 89,
        icon: Icons.diamond_rounded,
        chatSymbol: '💠',
        assetPath: 'assets/images/gifts/crystal_hunt.png',
        colors: [Color(0xFF16D9E3), Color(0xFF6D5DF6)],
      ),
      GiftItem(
        id: 'event_firework',
        name: 'Firework',
        category: GiftCategory.event,
        coins: 129,
        icon: Icons.celebration_rounded,
        chatSymbol: '🎆',
        assetPath: 'assets/images/gifts/event_firework.png',
        colors: [Color(0xFFFF7A45), Color(0xFF8C5CF6)],
      ),
      GiftItem(
        id: 'event_trophy',
        name: 'Trophy',
        category: GiftCategory.event,
        coins: 299,
        icon: Icons.emoji_events_rounded,
        chatSymbol: '🏆',
        assetPath: 'assets/images/gifts/event_trophy.png',
        colors: [Color(0xFFFFD166), Color(0xFFFF5F7E)],
      ),
      GiftItem(
        id: 'svip_dragon',
        name: 'SVIP Dragon',
        category: GiftCategory.svip,
        coins: 699,
        icon: Icons.auto_awesome_rounded,
        chatSymbol: '🐉',
        assetPath: 'assets/images/gifts/svip_dragon.png',
        colors: [Color(0xFF8C5CF6), Color(0xFF111827)],
      ),
      GiftItem(
        id: 'svip_throne',
        name: 'SVIP Throne',
        category: GiftCategory.svip,
        coins: 899,
        icon: Icons.chair_rounded,
        chatSymbol: '🪑',
        assetPath: 'assets/images/gifts/svip_throne.png',
        colors: [Color(0xFFFFD166), Color(0xFF8C5CF6)],
      ),
      GiftItem(
        id: 'premium_yacht',
        name: 'Yacht',
        category: GiftCategory.premium,
        coins: 1299,
        icon: Icons.sailing_rounded,
        chatSymbol: '🛥️',
        assetPath: 'assets/images/gifts/premium_yacht.png',
        colors: [Color(0xFF12C7B7), Color(0xFF111827)],
      ),
      GiftItem(
        id: 'premium_castle',
        name: 'Castle',
        category: GiftCategory.premium,
        coins: 1999,
        icon: Icons.castle_rounded,
        chatSymbol: '🏰',
        assetPath: 'assets/images/gifts/premium_castle.png',
        colors: [Color(0xFFC99A3B), Color(0xFF251538)],
      ),
      GiftItem(
        id: 'owned_love_bomb_3',
        name: 'Love x3',
        category: GiftCategory.baggage,
        coins: 0,
        icon: Icons.favorite_rounded,
        chatSymbol: '❤️',
        assetPath: 'assets/images/gifts/love_bomb.png',
        colors: [Color(0xFFFF5F7E), Color(0xFFFFC857)],
      ),
      GiftItem(
        id: 'owned_rocket_1',
        name: 'Rocket x1',
        category: GiftCategory.baggage,
        coins: 0,
        icon: Icons.rocket_launch_rounded,
        chatSymbol: '🚀',
        assetPath: 'assets/images/gifts/rocket.png',
        colors: [Color(0xFF18C7B7), Color(0xFF6C63FF)],
      ),
      GiftItem(
        id: 'owned_event_crown_2',
        name: 'Crown x2',
        category: GiftCategory.baggage,
        coins: 0,
        icon: Icons.workspace_premium_rounded,
        chatSymbol: '👑',
        assetPath: 'assets/images/gifts/royal_crown.png',
        colors: [Color(0xFFFFD166), Color(0xFF111827)],
      ),
    ];

    final seen = gifts.map((gift) => gift.id).toSet();
    return <GiftItem>[
      ...gifts,
      ...extras.where((gift) => seen.add(gift.id)),
    ];
  }
}
