apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: funkey
resources:
  - namespace.yaml
  - config.yaml
  - api.yaml
  - inbox.yaml
  - vibes.yaml
  - room-control.yaml
  - identity.yaml
  - profile-social.yaml
  - economy.yaml
  - game-platform.yaml
  - notification.yaml
  - graphql-bff.yaml
  - kafka-event-bridge.yaml
  - search.yaml
  - recommendation.yaml
  - realtime.yaml
  - worker.yaml
  - autoscaling.yaml
  - network-policy.yaml
