import 'package:flutter/material.dart';

import '../../../../shared/gradient_names/gradient_name_style.dart';
import 'store_models.dart';

class VmStoreCatalog {
  const VmStoreCatalog._();

  static const int gradientNamePriceCoins = 100000;
  static const int gradientNameDurationDays = 30;

  static List<VmStoreItem> get gradientNameItems {
    return GradientNameStyle.storeStyles.map((style) {
      return VmStoreItem(
        id: 'gradient_name_${style.id}_30d',
        title: style.label,
        subtitle: 'Gradient colored name effect across app for 30 days.',
        section: VmStoreSection.specialItems,
        type: VmStoreItemType.gradientName,
        rarity: VmStoreItemRarity.svip,
        priceCoins: gradientNamePriceCoins,
        isDynamicRemoteItem: true,
        isLimited: false,
        previewAssetKey: 'remote://gradient-name/${style.id}',
        durationDays: gradientNameDurationDays,
        colors: style.colors,
      );
    }).toList(growable: false);
  }

  static final List<VmStoreItem> dynamicItems = [
    const VmStoreItem(
      id: 'frame_neon_rose_30d',
      title: 'Neon Rose Frame',
      subtitle: 'Animated-style rose profile frame for 30 days.',
      section: VmStoreSection.frames,
      type: VmStoreItemType.frame,
      rarity: VmStoreItemRarity.premium,
      priceCoins: 1200,
      isDynamicRemoteItem: true,
      isLimited: false,
      previewAssetKey: 'cdn://store/frames/neon_rose_v1.webp',
      durationDays: 30,
      colors: [Color(0xFFE84C72), Color(0xFF6D5DF6)],
    ),
    const VmStoreItem(
      id: 'frame_royal_gold_perm',
      title: 'Royal Gold Frame',
      subtitle: 'Permanent luxury official-style gold frame.',
      section: VmStoreSection.frames,
      type: VmStoreItemType.frame,
      rarity: VmStoreItemRarity.vip,
      priceCoins: 8500,
      isDynamicRemoteItem: true,
      isLimited: false,
      previewAssetKey: 'cdn://store/frames/royal_gold_v1.webp',
      requiredVipLevel: 10,
      colors: [Color(0xFFC99A3B), Color(0xFFFFD36A)],
    ),
    const VmStoreItem(
      id: 'entrance_love_comet_7d',
      title: 'Love Comet Entrance',
      subtitle: 'Video plus sound entrance effect for rooms.',
      section: VmStoreSection.entranceEffects,
      type: VmStoreItemType.entranceEffect,
      rarity: VmStoreItemRarity.limited,
      priceCoins: 2800,
      isDynamicRemoteItem: true,
      isLimited: true,
      previewAssetKey: 'cdn://store/entrance/love_comet_v1.mp4',
      durationDays: 7,
      colors: [Color(0xFFE84C72), Color(0xFFFF8AA8)],
    ),
    const VmStoreItem(
      id: 'entrance_phoenix_30d',
      title: 'Phoenix Arrival',
      subtitle: 'Premium room entry video effect with sound.',
      section: VmStoreSection.entranceEffects,
      type: VmStoreItemType.entranceEffect,
      rarity: VmStoreItemRarity.svip,
      priceCoins: 9800,
      isDynamicRemoteItem: true,
      isLimited: false,
      previewAssetKey: 'cdn://store/entrance/phoenix_v1.mp4',
      requiredSvipLevel: 1,
      durationDays: 30,
      colors: [Color(0xFFFF7A1A), Color(0xFFC99A3B)],
    ),
    const VmStoreItem(
      id: 'bubble_midnight_glass_perm',
      title: 'Midnight Glass Bubble',
      subtitle: 'Premium chat bubble for room and Inbox display.',
      section: VmStoreSection.chatBubble,
      type: VmStoreItemType.chatBubble,
      rarity: VmStoreItemRarity.premium,
      priceCoins: 2200,
      isDynamicRemoteItem: true,
      isLimited: false,
      previewAssetKey: 'cdn://store/chat_bubbles/midnight_glass_v1.webp',
      colors: [Color(0xFF251538), Color(0xFF6D5DF6)],
    ),
    const VmStoreItem(
      id: 'room_bg_dark_luxury_perm',
      title: 'Luxury Dark Room',
      subtitle: 'Static premium room background theme.',
      section: VmStoreSection.roomBackground,
      type: VmStoreItemType.roomBackground,
      rarity: VmStoreItemRarity.premium,
      priceCoins: 4500,
      isDynamicRemoteItem: true,
      isLimited: false,
      previewAssetKey: 'cdn://store/room_backgrounds/luxury_dark_v1.webp',
      colors: [Color(0xFF08050D), Color(0xFF251538)],
    ),
    const VmStoreItem(
      id: 'room_bg_ocean_drive_30d',
      title: 'Ocean Drive Room',
      subtitle: 'Dynamic-ready room background config for 30 days.',
      section: VmStoreSection.roomBackground,
      type: VmStoreItemType.roomBackground,
      rarity: VmStoreItemRarity.limited,
      priceCoins: 5200,
      isDynamicRemoteItem: true,
      isLimited: true,
      previewAssetKey: 'cdn://store/room_backgrounds/ocean_drive_dynamic_v1.json',
      durationDays: 30,
      colors: [Color(0xFF12C7B7), Color(0xFF0C5B82)],
    ),
    const VmStoreItem(
      id: 'special_id_7_digits',
      title: '7 Digit Special ID',
      subtitle: 'Reserve a premium short numeric display ID.',
      section: VmStoreSection.specialId,
      type: VmStoreItemType.specialId,
      rarity: VmStoreItemRarity.official,
      priceCoins: 50000,
      isDynamicRemoteItem: true,
      isLimited: false,
      previewAssetKey: 'remote://special-id/7-digit',
      maxOwnable: 1,
      colors: [Color(0xFF251538), Color(0xFFC99A3B)],
    ),
    const VmStoreItem(
      id: 'bond_love_card',
      title: 'Love Card',
      subtitle: 'Create one Lover bond if you do not already have one.',
      section: VmStoreSection.loveAndBondCards,
      type: VmStoreItemType.loveCard,
      rarity: VmStoreItemRarity.premium,
      priceCoins: 9999,
      isDynamicRemoteItem: true,
      isLimited: false,
      previewAssetKey: 'cdn://store/bond_cards/love_card_v1.webp',
      maxOwnable: 1,
      colors: [Color(0xFFE84C72), Color(0xFFFFD36A)],
    ),
    const VmStoreItem(
      id: 'bond_brother_card',
      title: 'Brother Card',
      subtitle: 'Send to create a Brother bond after acceptance.',
      section: VmStoreSection.loveAndBondCards,
      type: VmStoreItemType.brotherCard,
      rarity: VmStoreItemRarity.common,
      priceCoins: 2500,
      isDynamicRemoteItem: true,
      isLimited: false,
      previewAssetKey: 'cdn://store/bond_cards/brother_card_v1.webp',
      colors: [Color(0xFF6D5DF6), Color(0xFF12C7B7)],
    ),
    const VmStoreItem(
      id: 'bond_sister_card',
      title: 'Sister Card',
      subtitle: 'Send to create a Sister bond after acceptance.',
      section: VmStoreSection.loveAndBondCards,
      type: VmStoreItemType.sisterCard,
      rarity: VmStoreItemRarity.common,
      priceCoins: 2500,
      isDynamicRemoteItem: true,
      isLimited: false,
      previewAssetKey: 'cdn://store/bond_cards/sister_card_v1.webp',
      colors: [Color(0xFFFF8AA8), Color(0xFF6D5DF6)],
    ),
    const VmStoreItem(
      id: 'bond_bestie_card',
      title: 'Bestie Card',
      subtitle: 'Send to create a Bestie bond after acceptance.',
      section: VmStoreSection.loveAndBondCards,
      type: VmStoreItemType.bestieCard,
      rarity: VmStoreItemRarity.common,
      priceCoins: 1800,
      isDynamicRemoteItem: true,
      isLimited: false,
      previewAssetKey: 'cdn://store/bond_cards/bestie_card_v1.webp',
      colors: [Color(0xFF12C7B7), Color(0xFFC99A3B)],
    ),
    const VmStoreItem(
      id: 'special_name_glow_30d',
      title: 'Name Glow',
      subtitle: 'Glowing name effect in room, profile and chat.',
      section: VmStoreSection.specialItems,
      type: VmStoreItemType.specialItem,
      rarity: VmStoreItemRarity.svip,
      priceCoins: 6000,
      isDynamicRemoteItem: true,
      isLimited: false,
      previewAssetKey: 'cdn://store/special/name_glow_v1.webp',
      requiredSvipLevel: 1,
      durationDays: 30,
      colors: [Color(0xFFFFD36A), Color(0xFFE84C72)],
    ),
    ...gradientNameItems,
  ];

  static List<VmStoreItem> visibleStoreItems({required bool hasLoveRelationship}) {
    return dynamicItems.where((item) {
      if (item.type == VmStoreItemType.loveCard && hasLoveRelationship) return false;
      return true;
    }).toList();
  }
}
