apiVersion: v1
kind: ConfigMap
metadata: {name: funkey-config}
data:
  APP_ENV: staging
  MEDIA_CDN_BASE_URL: https://cdn.staging.funkey.com/media
  KAFKA_BOOTSTRAP_SERVERS: funkey-kafka-bootstrap:9092
  KAFKA_SECURITY_PROTOCOL: PLAINTEXT
  KAFKA_TOPIC_REPLICATION_FACTOR: "3"
  OPENSEARCH_URL: http://funkey-opensearch:9200
  FUNKEY_REGION: staging-primary
  FUNKEY_HOME_REGION: staging-primary
  ECONOMY_WRITER_REGION: staging-primary
