apiVersion: apps/v1
kind: Deployment
metadata: {name: funkey-api-stable}
spec:
  replicas: 1
  template:
    spec:
      nodeSelector: null
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: funkey-realtime}
spec:
  replicas: 1
  template:
    spec:
      nodeSelector: null
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: funkey-worker}
spec:
  template:
    spec:
      nodeSelector: null
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {name: funkey-api}
spec: {minReplicas: 1, maxReplicas: 1}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {name: funkey-realtime}
spec: {minReplicas: 1, maxReplicas: 1}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata: {name: funkey-worker-notification}
spec: {minReplicaCount: 1, maxReplicaCount: 1}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata: {name: funkey-worker-media}
spec: {minReplicaCount: 1, maxReplicaCount: 1}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata: {name: funkey-worker-fanout}
spec: {minReplicaCount: 1, maxReplicaCount: 1}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata: {name: funkey-worker-maintenance}
spec: {minReplicaCount: 1, maxReplicaCount: 1}
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: funkey-notification}
spec:
  replicas: 1
  template:
    spec:
      nodeSelector: null
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: funkey-notification-provider}
spec:
  replicas: 1
  template:
    spec:
      nodeSelector: null
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {name: funkey-notification}
spec: {minReplicas: 1, maxReplicas: 1}
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: funkey-graphql-bff}
spec:
  replicas: 1
  template:
    spec:
      nodeSelector: null
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {name: funkey-graphql-bff}
spec: {minReplicas: 1, maxReplicas: 1}
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: funkey-kafka-event-bridge}
spec:
  replicas: 0
  template:
    spec:
      nodeSelector: null
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {name: funkey-kafka-event-bridge}
$patch: delete
