from sqlalchemy.orm import Session

from app.models.room import Room
from app.models.user import User
from app.models.call_session import CallSession, CallParticipant, CallSessionStatus, CallParticipantStatus
from app.services import ban_service, role_service
from app.services.permissions.media_room_permission_service import evaluate_media_room_permission

MEDIA_REALTIME_ACTIONS = {
    "join_room",
    "create_transport",
    "connect_transport",
    "produce_audio",
    "produce_video",
    "consume_audio",
    "pause_producer",
    "resume_producer",
    "close_producer",
    "leave_room",
    "join_seat",
    "leave_seat",
    "start_room_music",
    "stop_room_music",
}

_MEDIA_ACTIONS_REQUIRING_ROOM = {
    "join_room",
    "create_transport",
    "connect_transport",
    "produce_audio",
    "consume_audio",
    "pause_producer",
    "resume_producer",
    "close_producer",
    "join_seat",
    "leave_seat",
    "start_room_music",
    "stop_room_music",
}


def _role_values(user: User) -> list[str]:
    return [role.value for role in role_service.get_user_roles(user)]


def _primary_role_value(user: User) -> str:
    return role_service.get_primary_role(user).value


def _room_lookup(db: Session, room_public_id: str | None) -> Room | None:
    clean = (room_public_id or "").strip()
    if not clean:
        return None
    return db.query(Room).filter(Room.room_public_id == clean).first()


def _permission_set(action: str) -> list[str]:
    base = ["AUTHENTICATED_MEDIA_SOCKET"]
    if action in {"join_room", "consume_audio"}:
        base.append("ROOM_ACCESS_REQUIRED")
    if action in {"produce_audio", "join_seat"}:
        base.append("MIC_OR_SEAT_PERMISSION_REQUIRED")
    if action in {"pause_producer", "resume_producer", "close_producer"}:
        base.append("PRODUCER_OWNER_REQUIRED")
    if action in {"start_room_music", "stop_room_music"}:
        base.append("ROOM_MUSIC_CONTROL_REQUIRED")
    return base


def verify_media_realtime_request(
    *,
    db: Session,
    user: User,
    room_public_id: str | None,
    requested_action: str,
    device_id: str | None = None,
) -> dict:
    """Single backend source of truth for mediasoup/signaling authorization.

    The external mediasoup signaling server must call this endpoint after JWT
    verification and before allowing room join, transport creation, produce,
    consume, or seat actions. This service intentionally never trusts user_id,
    roles, or room permissions from the client payload.
    """
    action = (requested_action or "join_room").strip().lower()
    if action not in MEDIA_REALTIME_ACTIONS:
        return _payload(
            allowed=False,
            reason="Unsupported media realtime action.",
            user=user,
            room_public_id=room_public_id,
            requested_action=action,
            permissions=[],
            room=None,
            device_id=device_id,
        )

    if not user.is_active:
        return _payload(
            allowed=False,
            reason="User is inactive.",
            user=user,
            room_public_id=room_public_id,
            requested_action=action,
            permissions=[],
            room=None,
            device_id=device_id,
        )
    if user.is_banned:
        return _payload(
            allowed=False,
            reason="User is banned.",
            user=user,
            room_public_id=room_public_id,
            requested_action=action,
            permissions=[],
            room=None,
            device_id=device_id,
        )
    if ban_service.is_device_banned(db, device_id):
        return _payload(
            allowed=False,
            reason="Device is banned.",
            user=user,
            room_public_id=room_public_id,
            requested_action=action,
            permissions=[],
            room=None,
            device_id=device_id,
        )

    room = _room_lookup(db, room_public_id)
    # Call media namespaces are generated by FastAPI, never arbitrary client
    # rooms. Both call APIs share these persisted session/participant records.
    if room is None and (room_public_id or "").startswith("call_room_"):
        call = db.query(CallSession).filter(CallSession.room_public_id == room_public_id).first()
        participant = None if call is None else db.query(CallParticipant).filter(
            CallParticipant.call_session_id == call.id,
            CallParticipant.user_id == user.id,
        ).first()
        allowed = bool(
            call is not None
            and call.status in {CallSessionStatus.RINGING, CallSessionStatus.CONNECTING, CallSessionStatus.ACTIVE}
            and participant is not None
            and participant.status == CallParticipantStatus.JOINED
            and action not in {"start_room_music", "stop_room_music", "join_seat", "leave_seat"}
            and (action != "produce_video" or call.is_video_enabled)
        )
        return _payload(
            allowed=allowed, reason=None if allowed else "Active call participation required.",
            user=user, room_public_id=room_public_id, requested_action=action,
            permissions=["CALL_PARTICIPANT_REQUIRED"], room=None, device_id=device_id,
        )
    if action == "produce_video":
        return _payload(
            allowed=False, reason="Video publishing is only supported in video calls.",
            user=user, room_public_id=room_public_id, requested_action=action,
            permissions=[], room=room, device_id=device_id,
        )
    if action in _MEDIA_ACTIONS_REQUIRING_ROOM and not room_public_id:
        return _payload(
            allowed=False,
            reason="room_public_id is required for this media action.",
            user=user,
            room_public_id=room_public_id,
            requested_action=action,
            permissions=[],
            room=None,
            device_id=device_id,
        )
    if room_public_id and room is None:
        return _payload(
            allowed=False,
            reason="Room not found.",
            user=user,
            room_public_id=room_public_id,
            requested_action=action,
            permissions=[],
            room=None,
            device_id=device_id,
        )
    if room is not None and not room.is_active:
        return _payload(
            allowed=False,
            reason="Room is inactive.",
            user=user,
            room_public_id=room_public_id,
            requested_action=action,
            permissions=[],
            room=room,
            device_id=device_id,
        )

    permissions = _permission_set(action)
    permission_context: dict = {}
    if room is not None and action in _MEDIA_ACTIONS_REQUIRING_ROOM:
        decision = evaluate_media_room_permission(
            db=db,
            user=user,
            room=room,
            action=action,
            device_id=device_id,
        )
        permission_context = decision.context
        if not decision.allowed:
            return _payload(
                allowed=False,
                reason=decision.reason,
                user=user,
                room_public_id=room_public_id,
                requested_action=action,
                permissions=decision.permissions,
                room=room,
                device_id=device_id,
                permission_context=permission_context,
            )
        permissions = [*permissions, *decision.permissions]

    return _payload(
        allowed=True,
        reason=None,
        user=user,
        room_public_id=room_public_id,
        requested_action=action,
        permissions=permissions,
        room=room,
        device_id=device_id,
        permission_context=permission_context,
    )


def _payload(
    *,
    allowed: bool,
    reason: str | None,
    user: User,
    room_public_id: str | None,
    requested_action: str,
    permissions: list[str],
    room: Room | None,
    device_id: str | None,
    permission_context: dict | None = None,
) -> dict:
    return {
        "allowed": allowed,
        "reason": reason,
        "user": {
            "user_id": user.id,
            "public_user_id": user.public_user_id,
            "username": user.username,
            "display_name": user.display_name,
            "avatar_url": user.avatar_url,
            "roles": _role_values(user),
            "primary_role": _primary_role_value(user),
            "is_active": user.is_active,
            "is_banned": user.is_banned,
        },
        "room_public_id": room_public_id,
        "requested_action": requested_action,
        "permissions": list(dict.fromkeys(permissions)),
        "mediasoup_context": {
            "room_public_id": getattr(room, "room_public_id", room_public_id),
            "room_name": getattr(room, "name", None),
            "room_is_secret": bool(getattr(room, "is_secret", False)),
            "room_is_locked": bool(getattr(room, "is_locked", False)),
            "room_is_members_only": bool(getattr(room, "is_members_only", False)),
            "room_apply_only_mode_enabled": bool(getattr(room, "apply_only_mode_enabled", False)),
            "device_id_present": bool((device_id or "").strip()),
            "permission_context": permission_context or {},
            "must_ignore_client_user_id": True,
            "must_ignore_client_roles": True,
            "server_verified_identity": True,
        },
    }
